### ISSUE TITLE
Add: --delete-ami to default path

### ISSUE THREAD

**Issue by cuppett** [eformat/sno-for-100#11]
Would be nice to clean up (and they have an option for --delete-ami on the tool). However, I got this error trying it with that flag enabled:

Got this error when applying it:
```
[INFO] 2022-11-24 08:44:03,949 ec2-spot-converter - [STEP 26/26] Deregister image... 
Traceback (most recent call last):
  File "/home/scuppett/bin/ec2-spot-converter", line 1621, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/scuppett/bin/ec2-spot-converter", line 1587, in main
    return_code, reason, keys = step["Function"]()
                                ^^^^^^^^^^^^^^^^^^
  File "/home/scuppett/bin/ec2-spot-converter", line 1212, in deregister_image
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scuppett/bin/ec2-spot-converter", line 1212, in <listcomp>
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
                ~~~^^^^^^^
KeyError: 'Ebs'
```

**Comment by cuppett** [comment]
I think this is resolved by: 8e4289f0db2274772adfd8dbdd28c3bb4dc8a188
